// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
    const ElButton: typeof import('element-plus/es')['ElButton']
    const ElCard: typeof import('element-plus/es')['ElCard']
    const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    const ElInput: typeof import('element-plus/es')['ElInput']
    const ElOption: typeof import('element-plus/es')['ElOption']
    const ElSelect: typeof import('element-plus/es')['ElSelect']
    const ElTabPane: typeof import('element-plus/es')['ElTabPane']
    const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
